### ISSUE TITLE
Need to Verify GDAX use UTC

### ISSUE THREAD

**Issue by giantwhale** [giantwhale/qfin#1]
We use the UTC from System time as the timestamp for the quote data, while we use time pulled from the GDAX exchange as the timestamp for the trade data.  Need to verify GDAX use UTC time as well.

**Comment by willguxy** [comment]
According to the return from `public_client.get_product_trades(product_id='ETH-USD')`, the timestamps are in UTC.

**Comment by giantwhale** [comment]
verified from the official doc, https://docs.gdax.com/#selecting-a-timestamp
